---
- hosts: localhost
  connection: local
  become: true
  vars:
  tasks:
    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing dumb-init
      apt:
        deb: "https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb"

    - name: Installing Postfix
      apt:
        name: "{{ item }}"
        state: "installed"
        install_recommends: no
      with_items:
        - 'postfix'
        - 'mailutils'
